version: '3'
services:
  auth-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    ports:
      - '5432:5432'
    volumes:
      - ./auth-data/postgres:/var/lib/postgresql/data/
  chat-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chat_pass
      POSTGRES_DB: chat_db
    ports:
      - '5433:5432'
    volumes:
      - ./chat-data/postgres:/var/lib/postgresql/data/
  redis:
    image: redis:latest
    command:
      - 'redis-server'
    ports:
      - '6379:6379'
