version: '3'
services:
  auth-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    ports:
      - '5432:5432'
    volumes:
      - ./auth-data/postgres:/var/lib/postgresql/data/
  redis:
    image: redis:latest
    command:
      - 'redis-server'
    ports:
      - '6379:6379'
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ./media-data/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=media_user
      - MONGO_INITDB_ROOT_PASSWORD=media_pass
