export enum ActionTypes {
  // AuthActions
  CHECK_SESSION = 'CHECK_SESSION',
  LOGOUT = 'LOGOUT',

  LOGIN_START = 'LOGIN_START',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAIL = 'LOGIN_FAIL',

  REGISTER_START = 'REGISTER_START',
  REGISTER_SUCCESS = 'REGISTER_SUCCESS',
  REGISTER_FAIL = 'REGISTER_FAIL',

  // ContactsActions
  LIST_CONTACTS_START = 'LIST_CONTACTS_START',
  LIST_CONTACTS_SUCCESS = 'LIST_CONTACTS_SUCCESS',
  LIST_CONTACTS_FAIL = 'LIST_CONTACTS_FAIL',
}
